apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "unique.fullname" . }}-migration-{{ .Release.Revision }}
  labels:
    {{- include "unique.labels" . | nindent 4 }}
    app: mysql-init
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    helm.sh/hook: post-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels: { app: mysql-init }
    spec:
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          {{- include "unique.migrationContainer" . | nindent 10 }}
          args: ["up"]
