{{- if .Values.serviceAccount.create }}
{{- range $component := list "api" "auth" "front" "mail" "discord" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unique.serviceAccountName" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component) }}
  labels:
    {{- include "unique.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $.Values.serviceAccount.automount }}
{{- end }}
{{- end }}
