{{- range $service := list
  (dict "name" "api" "app" "unique-api" "port" 80 "target" 8080)
  (dict "name" "auth" "app" "unique-auth" "port" 80 "target" 8080)
  (dict "name" "front" "app" "unique-front" "port" 80 "target" 3000)
  (dict "name" "mailserver" "app" "unique-mail" "port" 80 "target" 8080)
  (dict "name" "mysql" "app" "mysql" "port" 3306 "target" 3306)
}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  labels:
    {{- include "unique.labels" $ | nindent 4 }}
    app: {{ $service.app }}
  {{- if $service.name | eq "mysql" }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  {{- end }}
spec:
  type: ClusterIP
  selector: { app: {{ $service.app }} }
  ports:
    - { name: tcp, protocol: TCP, port: {{ $service.port }}, targetPort: {{ $service.target }} }
{{- end }}
{{- if .Values.internalBlocker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: internal-blocker
  labels:
    {{- include "unique.labels" . | nindent 4 }}
spec:
  selector: { app: internal-blocker }
  ports:
    - { name: http, protocol: TCP, port: 80, targetPort: 80 }
{{- end }}
