apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./api.yaml
  - ./front.yaml
  - ./ingress.yaml
  - ./auth.yaml
  - ./db.yaml
  - ./pvc.yaml
  - ./harbor.yaml
  - ./mysql-init-job.yaml
  - ./imageUpdater.yaml
  - ./mail.yaml
  - ./hpa.yaml
  # - ./internal-policy.yaml
