apiVersion: v1
kind: ServiceAccount
metadata:
  name: unique-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unique-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unique-front
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unique-discord
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unique-mail
