apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
resources:
  - api-secret.yaml
  - frontend-secret.yaml
  - mysql-secret.yaml
  - auth-secret.yaml
  - mail-secret.yaml
  - discord-secret.yaml
